version: 2
jobs:
  build:
    environment:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
      - image: circleci/postgres:11

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cp .circleci/database.yml config/database.yml
      - run: cp .circleci/application.yml config/application.yml
      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load

      - run:
          name: run tests
          command: RAILS_ENV=test bundle exec rspec

      # run rails_best_practices!
      - run:
          name: run rails best practices
          command: RAILS_ENV=test bundle exec rake rails_best_practices

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results